const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const ts=require('typescript');
function load(path){const code=ts.transpileModule(fs.readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;const m={exports:{}};new Function('exports','module',code)(m.exports,m);return m.exports;}
const {threadComments}=load('lib/community.ts');const {inQuietHours,extraPreference}=load('supabase/functions/push-dispatch/preferences.ts');
test('reply chains remain ordered at any depth',()=>{const rows=[{id:'root'},{id:'sibling',parent_comment_id:'root'},{id:'deep',parent_comment_id:'reply'},{id:'reply',parent_comment_id:'sibling'}];assert.deepEqual(threadComments(rows).map(x=>[x.id,x.depth]),[['root',0],['sibling',1],['reply',2],['deep',3]])});
test('hidden parent does not hide visible descendant',()=>{assert.deepEqual(threadComments([{id:'orphan',parent_comment_id:'blocked'},{id:'child',parent_comment_id:'orphan'}]).map(x=>[x.id,x.depth]),[['orphan',0],['child',1]])});
test('malformed cycles render each comment once',()=>{const rows=threadComments([{id:'a',parent_comment_id:'b'},{id:'b',parent_comment_id:'a'}]);assert.equal(new Set(rows.map(x=>x.id)).size,2);assert.equal(rows.length,2)});
test('overnight quiet hours respect timezone and exact boundaries',()=>{const p={quiet_enabled:true,quiet_start:1320,quiet_end:420,timezone:'America/New_York'};assert.equal(inQuietHours(p,new Date('2026-10-05T01:59:00Z')),false);assert.equal(inQuietHours(p,new Date('2026-10-05T02:00:00Z')),true);assert.equal(inQuietHours(p,new Date('2026-10-05T10:59:00Z')),true);assert.equal(inQuietHours(p,new Date('2026-10-05T11:00:00Z')),false)});
test('daytime windows and DST winter offsets work',()=>{const p={quiet_enabled:true,quiet_start:540,quiet_end:1020,timezone:'America/New_York'};assert.equal(inQuietHours(p,new Date('2026-12-05T14:00:00Z')),true);assert.equal(inQuietHours(p,new Date('2026-12-05T22:00:00Z')),false);assert.equal(inQuietHours({...p,quiet_enabled:false}),false)});
test('replies, followed posts and supplies have independent preferences',()=>{assert.equal(extraPreference('community_reply'),'notify_replies');assert.equal(extraPreference('community_follow'),'notify_followed_posts');assert.equal(extraPreference('supply_match'),'notify_supplies');assert.equal(extraPreference('help'),null)});
