const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript');
function load(path){const code=ts.transpileModule(fs.readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText;const m={exports:{}};new Function('exports','module',code)(m.exports,m);return m.exports;}
const {permissionDescription,diagnosticSummary}=load('lib/troubleshooting.ts');const {C}=load('lib/theme.ts');const {WELCOME_SECTIONS}=load('lib/guide.ts');
function luminance(hex){const c=hex.slice(1).match(/../g).map(x=>parseInt(x,16)/255).map(x=>x<=.04045?x/12.92:((x+.055)/1.055)**2.4);return c[0]*.2126+c[1]*.7152+c[2]*.0722;}
function contrast(a,b){const x=luminance(a),y=luminance(b);return (Math.max(x,y)+.05)/(Math.min(x,y)+.05)}
test('core text and button colors have at least 4.5:1 contrast',()=>{for(const[a,b]of [[C.blue,C.white],[C.blue,C.sky],[C.gray,C.pale],[C.green,C.pale],[C.red,C.white],[C.navy,C.white]])assert.ok(contrast(a,b)>=4.5,`${a}/${b} contrast ${contrast(a,b)}`)});
test('permissions distinguish blocked, unrequested and quiet iOS delivery',()=>{assert.equal(permissionDescription({status:'denied'}),'Blocked in phone settings');assert.equal(permissionDescription({status:'undetermined'}),'Not yet enabled');assert.equal(permissionDescription({granted:false,ios:{status:3}}),'Quiet delivery allowed (provisional)');assert.equal(permissionDescription({granted:true}),'Allowed')});
test('shared diagnostics whitelist excludes credentials and account identity',()=>{const info={version:'1',build:'10',platform:'ios',permission:'Allowed',connection:'Connected',timezone:'UTC',email:'private@example.com',token:'secret-token',userId:'private-id'};const summary=diagnosticSummary(info);assert.ok(summary.includes('Build: 10'));for(const value of [info.email,info.token,info.userId])assert.ok(!summary.includes(value))});
test('welcome guide explains the core app areas and keeps beacon scope clear',()=>{assert.deepEqual(WELCOME_SECTIONS.map(x=>x.title),['Community','Help','T1 Beacon','Supply Locker','Groups']);assert.match(WELCOME_SECTIONS.find(x=>x.title==='T1 Beacon').description,/not an emergency service/)});
