import React,{useCallback,useState}from'react';
import{SafeAreaView,View,Text,TextInput,Pressable,FlatList,StyleSheet,KeyboardAvoidingView,Platform,Alert,Image}from'react-native';
import{useFocusEffect,useLocalSearchParams,router}from'expo-router';
import{Ionicons}from'@expo/vector-icons';
import{supabase}from'../lib/supabase';
import{useAuth}from'../lib/AuthContext';
import{C}from'../lib/theme';

const sameDay=(a:string,b:string)=>new Date(a).toDateString()===new Date(b).toDateString();
const dayLabel=(v:string)=>{const d=new Date(v),today=new Date(),y=new Date();y.setDate(today.getDate()-1);if(d.toDateString()===today.toDateString())return'Today';if(d.toDateString()===y.toDateString())return'Yesterday';return d.toLocaleDateString(undefined,{month:'short',day:'numeric',year:d.getFullYear()===today.getFullYear()?undefined:'numeric'})};
const timeLabel=(v:string)=>new Date(v).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});

export default function Chat(){
 const{id}=useLocalSearchParams<{id:string}>();const{session}=useAuth();const[msgs,setMsgs]=useState<any[]>([]);const[loading,setLoading]=useState(true);const[loadError,setLoadError]=useState('');const[sending,setSending]=useState(false);const[otherId,setOtherId]=useState('');const[text,setText]=useState('');const[canSend,setCanSend]=useState(true);const[title,setTitle]=useState('Conversation');const[avatar,setAvatar]=useState<string|null>(null);const[subtitle,setSubtitle]=useState('');
 const load=useCallback(async()=>{if(!id||!session)return;setLoadError('');const[m,members]=await Promise.all([
  supabase.from('messages').select('id,sender_id,body,created_at').eq('conversation_id',id).order('created_at',{ascending:false}),
  supabase.from('conversation_members').select('user_id,profiles!conversation_members_user_id_fkey(display_name,avatar_url,city,region)').eq('conversation_id',id)
 ]);if(m.error||members.error){setLoadError(m.error?.message||members.error?.message||'Could not load this conversation.');setLoading(false);return}if(m.data)setMsgs(m.data);setLoading(false);await supabase.rpc('mark_conversation_read',{cid:id});const{data:allowed}=await supabase.rpc('can_message',{cid:id});setCanSend(allowed!==false);const other=members.data?.find((x:any)=>x.user_id!==session.user.id);if(other){setOtherId(other.user_id);setTitle(other.profiles?.display_name||'T1Together Member');setAvatar(other.profiles?.avatar_url||null);setSubtitle([other.profiles?.city,other.profiles?.region].filter(Boolean).join(', '))}},[id,session]);
 useFocusEffect(useCallback(()=>{load();if(!id)return;const channel=supabase.channel('chat-'+id).on('postgres_changes',{event:'INSERT',schema:'public',table:'messages',filter:`conversation_id=eq.${id}`},payload=>{const incoming=payload.new as any;setMsgs(current=>current.some(x=>x.id===incoming.id)?current:[incoming,...current]);if(incoming.sender_id!==session?.user.id)supabase.rpc('mark_conversation_read',{cid:id})}).subscribe();return()=>{supabase.removeChannel(channel)}},[id,load,session?.user?.id]));
 async function send(){if(!text.trim()||!session||!id||sending)return;if(!canSend)return Alert.alert('Messaging unavailable','You can’t send messages in this conversation because one of you has blocked the other.');const body=text.trim();setSending(true);setText('');const{error}=await supabase.from('messages').insert({conversation_id:id,sender_id:session.user.id,body});setSending(false);if(error){setText(body);const blocked=error.code==='42501'||String(error.message).toLowerCase().includes('row-level security');return Alert.alert(blocked?'Messaging unavailable':'Could not send message',blocked?'You can’t send messages in this conversation because one of you has blocked the other.':error.message)}}
 function render({item,index}:{item:any,index:number}){const mine=item.sender_id===session?.user.id;const older=msgs[index+1];const showDay=!older||!sameDay(item.created_at,older.created_at);return <View>{showDay&&<View style={s.dayWrap}><Text style={s.day}>{dayLabel(item.created_at)}</Text></View>}<View style={[s.messageRow,mine&&s.messageRowMine]}><View style={[s.bubble,mine?s.mine:s.theirs]}><Text style={[s.message,mine&&s.messageMine]}>{item.body}</Text><Text style={[s.time,mine&&s.timeMine]}>{timeLabel(item.created_at)}</Text></View></View></View>}
 return <SafeAreaView style={s.safe}><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}>
  <View style={s.header}><Pressable style={s.headerBtn} onPress={()=>router.back()} accessibilityRole="button" accessibilityLabel="Back"><Ionicons name="chevron-back" size={26} color={C.blue}/></Pressable><Pressable style={s.person} onPress={()=>otherId&&router.push({pathname:'/member',params:{id:otherId}})}>{avatar?<Image source={{uri:avatar}} style={s.avatar}/>:<View style={s.avatarFallback}><Text style={s.initial}>{title.charAt(0).toUpperCase()}</Text></View>}<View style={s.personCopy}><Text style={s.title} numberOfLines={1}>{title}</Text><Text style={s.subtitle} numberOfLines={1}>{subtitle||'View profile'}</Text></View></Pressable><Pressable style={s.headerBtn} onPress={()=>otherId&&router.push({pathname:'/report',params:{type:'profile',id:otherId}})}><Ionicons name="ellipsis-horizontal" size={23} color={C.gray}/></Pressable></View>
  {!canSend&&<View style={s.blockBanner}><Ionicons name="ban-outline" size={17} color={C.gray}/><Text style={s.blocked}>Messaging is unavailable because one of you has blocked the other.</Text></View>}
  {loadError?<View style={s.errorState}><Ionicons name="cloud-offline-outline" size={29} color={C.blue}/><Text style={s.emptyTitle}>Couldn’t load conversation</Text><Text style={s.emptyText}>{loadError}</Text><Pressable onPress={load} style={s.retry}><Text style={s.retryText}>Try Again</Text></Pressable></View>:<FlatList data={msgs} inverted keyExtractor={x=>x.id} contentContainerStyle={s.list} keyboardDismissMode="interactive" renderItem={render} ListEmptyComponent={loading?<View style={s.empty}><Text style={s.emptyText}>Loading conversation…</Text></View>:<View style={s.empty}><Ionicons name="chatbubble-ellipses-outline" size={29} color={C.blue}/><Text style={s.emptyTitle}>Start the conversation</Text><Text style={s.emptyText}>Messages are private between you and this member.</Text></View>}/>} 
  <View style={s.compose}><TextInput style={[s.input,!canSend&&s.inputOff]} value={text} onChangeText={setText} placeholder={canSend?'Write a message…':'Messaging unavailable'} editable={canSend} multiline maxLength={1500}/><Pressable style={[s.send,(!canSend||!text.trim()||sending)&&s.sendOff]} onPress={send} disabled={!canSend||!text.trim()||sending} accessibilityRole="button" accessibilityLabel="Send message" accessibilityState={{disabled:!canSend||!text.trim()||sending}}><Ionicons name="arrow-up" size={21} color={C.white}/></Pressable></View>
 </KeyboardAvoidingView></SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:C.white},header:{minHeight:64,flexDirection:'row',alignItems:'center',paddingHorizontal:9,borderBottomWidth:1,borderColor:C.line},headerBtn:{width:42,height:42,alignItems:'center',justifyContent:'center'},person:{flex:1,flexDirection:'row',alignItems:'center',paddingVertical:7},avatar:{width:39,height:39,borderRadius:20,marginRight:9},avatarFallback:{width:39,height:39,borderRadius:20,backgroundColor:C.sky,alignItems:'center',justifyContent:'center',marginRight:9},initial:{fontWeight:'900',color:C.blue},personCopy:{flex:1},title:{fontWeight:'900',fontSize:16,color:C.navy},subtitle:{fontSize:10,color:C.gray,marginTop:2},list:{paddingHorizontal:13,paddingVertical:14,flexGrow:1,justifyContent:'flex-start'},dayWrap:{alignItems:'center',marginVertical:11},day:{fontSize:10,fontWeight:'800',color:C.gray,backgroundColor:C.pale,paddingHorizontal:10,paddingVertical:5,borderRadius:10},messageRow:{alignItems:'flex-start'},messageRowMine:{alignItems:'flex-end'},bubble:{maxWidth:'82%',paddingHorizontal:13,paddingTop:9,paddingBottom:6,borderRadius:18,marginVertical:3},mine:{backgroundColor:C.blue,borderBottomRightRadius:5},theirs:{backgroundColor:C.pale,borderBottomLeftRadius:5},message:{fontSize:15,lineHeight:20,color:C.navy},messageMine:{color:C.white},time:{fontSize:9,color:C.gray,marginTop:4,alignSelf:'flex-end'},timeMine:{color:'rgba(255,255,255,.72)'},compose:{flexDirection:'row',alignItems:'flex-end',gap:8,paddingHorizontal:12,paddingVertical:10,borderTopWidth:1,borderColor:C.line,backgroundColor:C.white},input:{flex:1,borderWidth:1,borderColor:C.line,borderRadius:21,paddingHorizontal:14,paddingTop:10,paddingBottom:10,maxHeight:110,fontSize:15},inputOff:{backgroundColor:C.pale},send:{width:44,height:44,borderRadius:21,backgroundColor:C.blue,alignItems:'center',justifyContent:'center'},sendOff:{opacity:.35},blockBanner:{flexDirection:'row',gap:7,alignItems:'center',justifyContent:'center',padding:9,backgroundColor:C.pale},blocked:{color:C.gray,fontSize:11},empty:{alignItems:'center',padding:30,transform:[{scaleY:-1}]},errorState:{flex:1,alignItems:'center',justifyContent:'center',padding:30},emptyTitle:{fontWeight:'900',fontSize:16,color:C.navy,marginTop:8},emptyText:{fontSize:12,color:C.gray,marginTop:4,textAlign:'center'},retry:{marginTop:14,paddingHorizontal:18,paddingVertical:11,borderRadius:12,backgroundColor:C.blue},retryText:{color:C.white,fontWeight:'900'}});
