import React,{useState}from'react';
import{SafeAreaView,View,Text,TextInput,Pressable,StyleSheet,Alert,KeyboardAvoidingView,Platform,ScrollView,Image}from'react-native';
import{router}from'expo-router';
import{Ionicons}from'@expo/vector-icons';
import * as ImagePicker from'expo-image-picker';
import{supabase}from'../lib/supabase';
import{useAuth}from'../lib/AuthContext';
import{C}from'../lib/theme';
const cats=['General','Newly Diagnosed','Devices','School','Travel','Parenting'];
export default function CreatePost(){
 const{session}=useAuth();const[body,setBody]=useState('');const[category,setCategory]=useState('General');const[busy,setBusy]=useState(false);const[photo,setPhoto]=useState<any>(null);
 async function choosePhoto(){const permission=await ImagePicker.requestMediaLibraryPermissionsAsync();if(!permission.granted)return Alert.alert('Photo access needed','Allow photo access to add a picture to your post.');const result=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],allowsEditing:false,quality:.8});if(!result.canceled)setPhoto(result.assets[0])}
 async function publish(){const clean=body.trim();if(!clean)return Alert.alert('Write something first','Add a question, experience, or update to your post.');if(clean.length>1500)return Alert.alert('Post is too long','Please keep posts under 1,500 characters.');if(!session)return;
 setBusy(true);let image_path:string|null=null;try{if(photo){const response=await fetch(photo.uri);const bytes=await response.arrayBuffer();const mime=photo.mimeType&&photo.mimeType.startsWith('image/')?photo.mimeType:'image/jpeg';const ext=mime==='image/png'?'png':mime==='image/webp'?'webp':'jpg';image_path=`${session.user.id}/${Date.now()}.${ext}`;const{error:up}=await supabase.storage.from('community-posts').upload(image_path,bytes,{contentType:mime,upsert:false});if(up)throw up}const{error}=await supabase.from('posts').insert({author_id:session.user.id,body:clean,category,image_path});if(error)throw error;router.replace('/(tabs)/community')}catch(e:any){if(image_path)await supabase.storage.from('community-posts').remove([image_path]);Alert.alert('Could not publish',e?.message||'Please try again.')}finally{setBusy(false)}}
 return <SafeAreaView style={s.safe}><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView contentContainerStyle={s.page} keyboardShouldPersistTaps="handled" keyboardDismissMode="interactive">
  <View style={s.header}><Pressable onPress={()=>router.back()} style={s.close}><Ionicons name="close" size={27} color={C.navy}/></Pressable><Text style={s.title}>Create Post</Text><Pressable onPress={publish} disabled={busy||!body.trim()} style={[s.publish,(!body.trim()||busy)&&s.disabled]}><Text style={s.publishText}>{busy?'Posting…':'Post'}</Text></Pressable></View>
  <Text style={s.prompt}>What would you like to share?</Text><TextInput autoFocus multiline maxLength={1500} value={body} onChangeText={setBody} placeholder="Ask a question, share an experience, or tell the community what's happening…" placeholderTextColor="#8294A7" style={s.input}/>
  <Text style={s.count}>{body.length}/1500</Text><Text style={s.label}>Photo <Text style={s.optional}>(optional, one photo)</Text></Text>{photo?<View style={s.photoCard}><Image source={{uri:photo.uri}} style={s.postPhoto}/><Pressable style={s.removePhoto} onPress={()=>setPhoto(null)}><Ionicons name="close" size={20} color={C.white}/></Pressable></View>:<Pressable style={s.addPhoto} onPress={choosePhoto}><Ionicons name="image-outline" size={21} color={C.blue}/><Text style={s.addPhotoText}>Add Photo</Text></Pressable>}<Text style={s.label}>Topic</Text><View style={s.chips}>{cats.map(c=><Pressable key={c} onPress={()=>setCategory(c)} style={[s.chip,category===c&&s.chipOn]}><Text style={[s.chipText,category===c&&s.chipTextOn]}>{c}</Text></Pressable>)}</View>
  <View style={s.reminder}><Ionicons name="people-outline" size={21} color={C.blue}/><Text style={s.reminderText}>Keep personal medical details private. Community posts are peer support, not medical advice.</Text></View>
 <View style={{height:24}}/></ScrollView></KeyboardAvoidingView></SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:C.white},page:{flexGrow:1,padding:20,paddingBottom:40},header:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:5},close:{width:42,height:42,alignItems:'center',justifyContent:'center'},title:{fontSize:18,fontWeight:'900',color:C.navy},publish:{backgroundColor:C.blue,borderRadius:20,paddingHorizontal:17,paddingVertical:10},disabled:{opacity:.4},publishText:{color:C.white,fontWeight:'900'},prompt:{fontSize:23,fontWeight:'900',color:C.navy,marginTop:28},input:{fontSize:18,lineHeight:27,color:C.navy,minHeight:180,textAlignVertical:'top',marginTop:12},count:{textAlign:'right',fontSize:12,color:C.gray},label:{fontSize:15,fontWeight:'900',color:C.navy,marginTop:18,marginBottom:10},optional:{fontWeight:'600',color:C.gray},addPhoto:{height:52,borderWidth:1,borderColor:C.line,borderRadius:14,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8,backgroundColor:C.pale},addPhotoText:{color:C.blue,fontWeight:'900'},photoCard:{position:'relative',borderRadius:18,overflow:'hidden',backgroundColor:C.pale},postPhoto:{width:'100%',height:230,resizeMode:'cover'},removePhoto:{position:'absolute',right:10,top:10,width:34,height:34,borderRadius:17,backgroundColor:'rgba(0,0,0,.65)',alignItems:'center',justifyContent:'center'},chips:{flexDirection:'row',flexWrap:'wrap',gap:8},chip:{paddingHorizontal:13,paddingVertical:9,borderRadius:20,backgroundColor:C.pale,borderWidth:1,borderColor:C.line},chipOn:{backgroundColor:C.sky,borderColor:C.blue},chipText:{fontSize:13,fontWeight:'700',color:C.gray},chipTextOn:{color:C.blue},reminder:{flexDirection:'row',gap:10,backgroundColor:C.pale,padding:15,borderRadius:16,marginTop:25},reminderText:{flex:1,color:C.gray,fontSize:13,lineHeight:19}});