import React,{useCallback,useState} from 'react';
import {Text,View,Pressable,Alert} from 'react-native';
import {router,useFocusEffect,useLocalSearchParams} from 'expo-router';
import {Screen,Action,ui} from '../components/Screen';
import {supabase} from '../lib/supabase';
import {useAuth} from '../lib/AuthContext';
export default function GroupDetail(){
 const{id}=useLocalSearchParams<{id:string}>();const{session}=useAuth();const[group,setGroup]=useState<any>(null);const[posts,setPosts]=useState<any[]>([]);const[joined,setJoined]=useState(false);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[error,setError]=useState('');
 const load=useCallback(async()=>{if(!id||!session)return;setError('');const[g,p,m]=await Promise.all([supabase.from('community_groups').select('*').eq('id',id).single(),supabase.from('posts').select('id,body,category,question_answered,created_at,profiles!posts_author_id_fkey(display_name)').eq('group_id',id).order('created_at',{ascending:false}).limit(100),supabase.from('community_group_memberships').select('group_id').eq('group_id',id).eq('user_id',session.user.id).maybeSingle()]);if(g.error||p.error||m.error)setError(g.error?.message||p.error?.message||m.error?.message||'Group unavailable');else{setGroup(g.data);setPosts(p.data||[]);setJoined(!!m.data)}setLoading(false)},[id,session?.user.id]);
 useFocusEffect(useCallback(()=>{load();if(!id)return;const ch=supabase.channel('group-posts-'+id).on('postgres_changes',{event:'*',schema:'public',table:'posts',filter:`group_id=eq.${id}`},()=>load()).subscribe();return()=>{supabase.removeChannel(ch)}},[load,id]));
 async function toggle(){if(!session||busy)return;setBusy(true);const{error}=joined?await supabase.from('community_group_memberships').delete().eq('user_id',session.user.id).eq('group_id',id):await supabase.from('community_group_memberships').insert({user_id:session.user.id,group_id:id});if(error)Alert.alert('Could not update membership',error.message);else await load();setBusy(false)}
 return <Screen title={group?.name||'Community Group'}>{loading?<Text style={ui.text}>Loading group…</Text>:error?<><Text accessibilityRole="alert" style={ui.error}>{error}</Text><Action label="Try again" onPress={load}/></>:<><Text style={ui.text}>{group?.description}</Text><Text style={[ui.text,{marginTop:10}]}>This is an open group. Its conversations are visible to signed-in members.</Text><Action secondary label={joined?'Leave group':'Join group'} onPress={toggle} busy={busy}/>{joined&&<Action label="Start a group conversation" onPress={()=>router.push({pathname:'/create-post',params:{groupId:id}})}/>}<Text accessibilityRole="header" style={[ui.heading,{marginTop:24}]}>Conversations</Text>{posts.length===0&&<Text style={ui.text}>No conversations yet. Join this group to start one.</Text>}{posts.map(p=><Pressable accessibilityRole="button" accessibilityLabel={`Open post by ${(p.profiles as any)?.display_name||'Member'}: ${p.body}`} key={p.id} style={ui.card} onPress={()=>router.push({pathname:'/post-detail',params:{id:p.id}})}><Text style={ui.heading}>{(p.profiles as any)?.display_name||'Member'}</Text><Text style={ui.text}>{p.category} · {new Date(p.created_at).toLocaleDateString()}</Text>{p.question_answered&&<Text style={ui.tag}>Question answered</Text>}<Text style={[ui.text,{marginTop:10}]}>{p.body}</Text></Pressable>)}</>}</Screen>;
}
