import React,{useCallback,useState}from'react';import{SafeAreaView,ScrollView,View,Text,Pressable,StyleSheet,RefreshControl}from'react-native';import{useFocusEffect,router}from'expo-router';import{Ionicons}from'@expo/vector-icons';import{supabase}from'../lib/supabase';import{useAuth}from'../lib/AuthContext';import{C}from'../lib/theme';

export default function Notifications(){const{session}=useAuth();const[rows,setRows]=useState<any[]>([]);const[refreshing,setRefreshing]=useState(false);
const load=useCallback(async()=>{if(!session)return;const{data}=await supabase.from('notifications').select('id,kind,title,body,route,entity_id,read_at,created_at').order('created_at',{ascending:false}).limit(100);setRows(data||[])},[session]);
useFocusEffect(useCallback(()=>{load();const timer=setInterval(load,3000);return()=>clearInterval(timer)},[load]));
async function refresh(){setRefreshing(true);await load();setRefreshing(false)}
async function open(x:any){if(!x.read_at)await supabase.rpc('mark_notification_read',{nid:x.id});if(x.kind==='help_response'&&x.entity_id)router.push({pathname:'/help-responses',params:{id:x.entity_id}});else if((x.kind==='help'||x.kind==='beacon')&&x.entity_id)router.push({pathname:'/help-detail',params:{id:x.entity_id}});else if(x.route)router.push(x.route as any);else load()}
async function markAll(){await supabase.rpc('mark_all_notifications_read');load()}
return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={refresh}/>}><View style={s.header}><Pressable onPress={()=>router.back()}><Ionicons name="chevron-back" size={27} color={C.blue}/></Pressable><Text style={s.h}>Notifications</Text><Pressable onPress={markAll}><Text style={s.mark}>Mark all read</Text></Pressable></View>{rows.length===0?<View style={s.empty}><Ionicons name="notifications-outline" size={30} color={C.blue}/><Text style={s.emptyTitle}>No notifications yet</Text><Text style={s.muted}>Help, Beacon and response alerts will appear here.</Text></View>:rows.map(x=><Pressable key={x.id} style={[s.card,!x.read_at&&s.unread]} onPress={()=>open(x)}><View style={s.icon}><Ionicons name={x.kind==='beacon'?'radio':x.kind==='help_response'?'heart':'help-buoy'} size={20} color={x.kind==='beacon'?C.red:C.blue}/></View><View style={{flex:1}}><View style={s.titleRow}><Text style={s.title}>{x.title}</Text>{!x.read_at&&<View style={s.dot}/>}</View><Text style={s.body}>{x.body}</Text><Text style={s.time}>{new Date(x.created_at).toLocaleString()}</Text></View></Pressable>)}</ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:C.white},page:{padding:20,paddingBottom:40},header:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:12,marginBottom:20},h:{fontSize:24,fontWeight:'900',color:C.navy},mark:{color:C.blue,fontWeight:'800',fontSize:12},empty:{padding:25,backgroundColor:C.pale,borderRadius:20,alignItems:'center'},emptyTitle:{fontSize:18,fontWeight:'900',color:C.navy,marginTop:9},muted:{color:C.gray,textAlign:'center',marginTop:5},card:{flexDirection:'row',gap:12,padding:16,borderWidth:1,borderColor:C.line,borderRadius:17,marginBottom:10},unread:{backgroundColor:C.pale},icon:{width:40,height:40,borderRadius:20,backgroundColor:C.sky,alignItems:'center',justifyContent:'center'},titleRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},title:{fontWeight:'900',color:C.navy,fontSize:15,flex:1},dot:{width:9,height:9,borderRadius:5,backgroundColor:C.blue,marginLeft:8},body:{color:C.gray,lineHeight:19,marginTop:4},time:{fontSize:10,color:C.gray,marginTop:7}});