import{useForegroundPolling}from'../lib/useForegroundPolling';
import React,{useCallback,useState}from'react';import{SafeAreaView,ScrollView,View,Text,Pressable,StyleSheet,RefreshControl}from'react-native';import{useFocusEffect,useLocalSearchParams,router}from'expo-router';import{Ionicons}from'@expo/vector-icons';import{supabase}from'../lib/supabase';import{useAuth}from'../lib/AuthContext';import{C}from'../lib/theme';import{notificationRoute,syncNotificationBadge}from'../lib/notifications';

export default function Notifications(){const[focused,setFocused]=useState(false);useFocusEffect(useCallback(()=>{setFocused(true);return()=>setFocused(false)},[]));const{section}=useLocalSearchParams<{section?:string}>();const communityKinds=['community_comment','community_reply','community_support','community_follow'];const helpKinds=['help','beacon','help_response','supply','supply_match'];const kinds=section==='community'?communityKinds:section==='help'?helpKinds:null;const{session}=useAuth();const[rows,setRows]=useState<any[]>([]);const[refreshing,setRefreshing]=useState(false);
const load=useCallback(async()=>{if(!session)return;let query=supabase.from('notifications').select('id,kind,title,body,route,entity_id,comment_id,read_at,created_at').order('created_at',{ascending:false}).limit(100);if(kinds)query=query.in('kind',kinds);const{data}=await query;setRows(data||[])},[session,section]);
useForegroundPolling(load,focused&&!!session);
async function refresh(){setRefreshing(true);await load();setRefreshing(false)}
async function open(x:any){if(!x.read_at)await supabase.rpc('mark_notification_read',{nid:x.id});await syncNotificationBadge();router.push(notificationRoute({kind:x.kind,entity_id:x.entity_id,route:x.route,comment_id:x.comment_id}))}
async function markAll(){if(!session)return;let query=supabase.from('notifications').update({read_at:new Date().toISOString()}).eq('user_id',session!.user.id).is('read_at',null);if(kinds)query=query.in('kind',kinds);await query;await syncNotificationBadge();load()}
return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={refresh}/>}><View style={s.header}><Pressable accessibilityRole="button" accessibilityLabel="Go back" onPress={()=>router.back()}><Ionicons accessible={false} importantForAccessibility="no" name="chevron-back" size={27} color={C.blue}/></Pressable><Text accessibilityRole="header" style={s.h}>{section==='community'?'Community Updates':section==='help'?'Help Updates':'Notifications'}</Text><Pressable accessibilityRole="button" onPress={markAll}><Text style={s.mark}>Mark All Read</Text></Pressable></View>{rows.length===0?<View style={s.empty}><Ionicons accessible={false} importantForAccessibility="no" name="notifications-outline" size={30} color={C.blue}/><Text style={s.emptyTitle}>No Notifications Yet</Text><Text style={s.muted}>{section==='community'?'Comments, replies and support on your posts will appear here.':section==='help'?'Help, Beacon and Supply Locker updates will appear here.':'Community, Help and Supply Locker updates will appear here.'}</Text></View>:rows.map(x=><Pressable accessibilityRole="button" key={x.id} style={[s.card,!x.read_at&&s.unread]} onPress={()=>open(x)}><View style={s.icon}><Ionicons accessible={false} importantForAccessibility="no" name={communityKinds.includes(x.kind)?'people':x.kind==='beacon'?'radio':x.kind==='help_response'?'heart':'help-buoy'} size={20} color={x.kind==='beacon'?C.red:C.blue}/></View><View style={{flex:1}}><View style={s.titleRow}><Text accessibilityRole="header" style={s.title}>{x.title}</Text>{!x.read_at&&<View style={s.dot}/>}</View><Text style={s.body}>{x.body}</Text><Text style={s.time}>{new Date(x.created_at).toLocaleString()}</Text></View></Pressable>)}</ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:C.white},page:{padding:20,paddingBottom:40},header:{flexWrap:'wrap',flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:12,marginBottom:20},h:{flex:1,fontSize:20,fontWeight:'900',color:C.navy,marginHorizontal:8},mark:{color:C.blue,fontWeight:'800',fontSize:12},empty:{padding:25,backgroundColor:C.pale,borderRadius:20,alignItems:'center'},emptyTitle:{fontSize:18,fontWeight:'900',color:C.navy,marginTop:9},muted:{color:C.gray,textAlign:'center',marginTop:5},card:{flexDirection:'row',gap:12,padding:16,borderWidth:1,borderColor:C.line,borderRadius:17,marginBottom:10},unread:{backgroundColor:C.pale},icon:{width:40,height:40,borderRadius:20,backgroundColor:C.sky,alignItems:'center',justifyContent:'center'},titleRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},title:{fontWeight:'900',color:C.navy,fontSize:15,flex:1},dot:{width:9,height:9,borderRadius:5,backgroundColor:C.blue,marginLeft:8},body:{color:C.gray,lineHeight:19,marginTop:4},time:{fontSize:12,color:C.gray,marginTop:7}});
