import React,{useEffect,useState}from'react';import{SafeAreaView,View,Text,TextInput,Pressable,StyleSheet,Alert,ScrollView,KeyboardAvoidingView,Platform,Switch,Image}from'react-native';import{router}from'expo-router';import{Ionicons}from'@expo/vector-icons';import * as ImagePicker from'expo-image-picker';import{supabase}from'../lib/supabase';import{useAuth}from'../lib/AuthContext';import{C}from'../lib/theme';

const DEVICES=['Dexcom G6','Dexcom G7','Dexcom G7 15 Day','FreeStyle Libre 2','FreeStyle Libre 3','Omnipod DASH','Omnipod 5','Tandem t:slim X2','Tandem Mobi','Medtronic MiniMed 780G','iLet Bionic Pancreas','Insulin pens','Multiple Daily Injections (MDI)','Blood glucose meter'];
const INSULINS=['NovoLog / insulin aspart','Humalog / insulin lispro','Fiasp / faster aspart','Lyumjev / ultra-rapid lispro','Apidra / insulin glulisine','Lantus / insulin glargine','Basaglar / insulin glargine','Toujeo / insulin glargine U-300','Tresiba / insulin degludec'];
const EXPERIENCE=['Newly Diagnosed','Stage 1 T1D','Stage 2 T1D','Stage 3 T1D','Caregiver Experience','Parent of a Child with T1D','Parent of Multiple Children with T1D','CGMs','Insulin Pumps','MDI / Injections','Hybrid Closed Loop / AID','Lows / Hypoglycemia','Highs / Hyperglycemia','Ketones & Sick Days','Carb Counting','Exercise & Sports','School & 504 Plans','Travel & Flying','Insurance & Prior Authorizations','T1D Burnout & Emotional Support','Everyday T1D'];
const HELP=['Newly Diagnosed','CGMs','Pumps & AID','MDI / Injections','Lows','Highs & Ketones','School & 504 Plans','Travel','Exercise & Sports','Carb Counting','Insurance','Supplies & Refills','Device Troubleshooting','Caregiver Support','Everyday T1D'];
const toggle=(a:string[],x:string,set:(v:string[])=>void)=>set(a.includes(x)?a.filter(v=>v!==x):[...a,x]);

export default function Onboarding(){const{session}=useAuth();const[name,setName]=useState('');const[avatar,setAvatar]=useState<string|null>(null);const[bio,setBio]=useState('');const[city,setCity]=useState('');const[region,setRegion]=useState('MA');const[year,setYear]=useState('');const[devices,setDevices]=useState<string[]>([]);const[insulins,setInsulins]=useState<string[]>([]);const[experience,setExperience]=useState<string[]>([]);const[help,setHelp]=useState<string[]>([]);const[helper,setHelper]=useState(false);const[isPublic,setIsPublic]=useState(true);const[busy,setBusy]=useState(false);
useEffect(()=>{if(!session){router.replace('/welcome');return}supabase.from('profiles').select('display_name,avatar_url').eq('id',session.user.id).single().then(({data})=>{if(data){setName(data.display_name||'');setAvatar(data.avatar_url||null)}})},[session?.user?.id]);
async function photo(){if(!session)return;const p=await ImagePicker.requestMediaLibraryPermissionsAsync();if(!p.granted)return Alert.alert('Photo access needed','Allow photo access to choose a profile picture.');const r=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],allowsEditing:true,aspect:[1,1],quality:.75});if(r.canceled)return;setBusy(true);try{const a=r.assets[0],resp=await fetch(a.uri),bytes=await resp.arrayBuffer();const mime=a.mimeType?.startsWith('image/')?a.mimeType:'image/jpeg';const ext=mime==='image/png'?'png':mime==='image/webp'?'webp':'jpg';const path=`${session.user.id}/avatar.${ext}`;const{error}=await supabase.storage.from('avatars').upload(path,bytes,{contentType:mime,upsert:true});if(error)throw error;const{data}=supabase.storage.from('avatars').getPublicUrl(path);const url=`${data.publicUrl}?v=${Date.now()}`;await supabase.from('profiles').update({avatar_url:url}).eq('id',session.user.id);setAvatar(url)}catch(e:any){Alert.alert('Could not add photo',e?.message||'Please try again.')}finally{setBusy(false)}}
async function save(){if(!session||name.trim().length<2)return Alert.alert('Complete your profile','Please enter a display name.');setBusy(true);const{error}=await supabase.from('profiles').update({display_name:name.trim(),bio:bio.trim(),city:city.trim(),region:region.trim(),diagnosis_year:year?Number(year):null,devices,insulins,experience_topics:experience,help_topics:help,helper_enabled:helper,is_public:isPublic,onboarding_completed:true}).eq('id',session.user.id);setBusy(false);if(error)return Alert.alert('Could not save profile',error.message);router.replace('/(tabs)/home')}
const chips=(items:string[],selected:string[],set:(v:string[])=>void)=><View style={s.chips}>{items.map(x=><Pressable key={x} onPress={()=>toggle(selected,x,set)} style={[s.chip,selected.includes(x)&&s.chipOn]}><Text style={[s.chipText,selected.includes(x)&&s.chipTextOn]}>{x}</Text></Pressable>)}</View>;
return <SafeAreaView style={s.safe}><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView contentContainerStyle={s.page} keyboardShouldPersistTaps="handled"><Text style={s.step}>WELCOME TO T1TOGETHER</Text><Text style={s.h}>Build Your Profile</Text><Text style={s.sub}>Tell the community a little about your T1D experience. You can change any of this later in Settings.</Text>
<Pressable style={s.photoRow} onPress={photo}>{avatar?<Image source={{uri:avatar}} style={s.avatar}/>:<View style={s.avatar}><Ionicons name="camera-outline" size={28} color={C.blue}/></View>}<View><Text style={s.photoTitle}>{avatar?'Change Profile Photo':'Add a Profile Photo'}</Text><Text style={s.hint}>Optional</Text></View></Pressable>
<Text style={s.label}>Display Name</Text><TextInput style={s.input} value={name} onChangeText={setName}/>
<Text style={s.label}>About You</Text><TextInput style={[s.input,{height:90}]} multiline placeholder="T1D parent, living with T1D, what you're here for…" value={bio} onChangeText={setBio}/>
<Text style={s.label}>Community Area</Text><Text style={s.hint}>Only your general community area is shown publicly.</Text><View style={s.row}><TextInput style={[s.input,{flex:1}]} placeholder="City" value={city} onChangeText={setCity}/><TextInput style={[s.input,{width:90}]} placeholder="State" value={region} onChangeText={setRegion}/></View>
<Text style={s.label}>Diagnosis Year <Text style={s.optional}>(optional)</Text></Text><TextInput style={s.input} value={year} onChangeText={x=>setYear(x.replace(/[^0-9]/g,'').slice(0,4))} placeholder="e.g. 2024" keyboardType="number-pad"/>
<Text style={s.label}>Devices <Text style={s.optional}>(optional)</Text></Text>{chips(DEVICES,devices,setDevices)}
<Text style={s.label}>Insulin Experience <Text style={s.optional}>(optional)</Text></Text>{chips(INSULINS,insulins,setInsulins)}
<Text style={s.label}>Your T1D Experience <Text style={s.optional}>(optional)</Text></Text>{chips(EXPERIENCE,experience,setExperience)}
<Text style={s.label}>I Can Help With <Text style={s.optional}>(optional)</Text></Text>{chips(HELP,help,setHelp)}
<View style={s.switchRow}><View style={{flex:1}}><Text style={s.switchTitle}>Helper Mode</Text><Text style={s.switchText}>Let nearby members know you're available to help.</Text></View><Switch value={helper} onValueChange={setHelper}/></View>
<View style={s.switchRow}><View style={{flex:1}}><Text style={s.switchTitle}>Discoverable Profile</Text><Text style={s.switchText}>Allow members to find you in Nearby and member search. Exact GPS coordinates are never shown.</Text></View><Switch value={isPublic} onValueChange={setIsPublic}/></View>
<View style={s.privacy}><Ionicons name="shield-checkmark-outline" size={20} color={C.blue}/><Text style={s.privacyText}>Your exact home location is never part of your public profile. T1Together uses reduced-precision location for nearby matching.</Text></View>
<Pressable style={[s.btn,busy&&{opacity:.6}]} onPress={save} disabled={busy}><Text style={s.bt}>{busy?'Saving…':'Complete Profile'}</Text></Pressable><Text style={s.bottom}>You can update these choices anytime in Profile & Settings.</Text></ScrollView></KeyboardAvoidingView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:C.white},page:{padding:24,paddingTop:36,paddingBottom:45},step:{fontSize:12,fontWeight:'900',color:C.blue,letterSpacing:1},h:{fontSize:31,fontWeight:'900',color:C.navy,marginTop:5},sub:{color:C.gray,fontSize:15,lineHeight:22,marginTop:7,marginBottom:18},photoRow:{flexDirection:'row',alignItems:'center',gap:13,padding:14,backgroundColor:C.pale,borderRadius:17,marginBottom:10},avatar:{width:58,height:58,borderRadius:29,backgroundColor:C.sky,alignItems:'center',justifyContent:'center'},photoTitle:{fontWeight:'900',color:C.navy},label:{fontWeight:'900',color:C.navy,marginTop:13,marginBottom:6},optional:{fontWeight:'600',color:C.gray},hint:{fontSize:12,color:C.gray,marginBottom:6},input:{borderWidth:1,borderColor:C.line,borderRadius:14,padding:13,fontSize:16,marginBottom:6},row:{flexDirection:'row',gap:8},chips:{flexDirection:'row',flexWrap:'wrap',gap:7,marginBottom:3},chip:{paddingHorizontal:11,paddingVertical:8,borderRadius:16,backgroundColor:C.pale,borderWidth:1,borderColor:C.line},chipOn:{backgroundColor:C.sky,borderColor:C.blue},chipText:{fontSize:12,fontWeight:'800',color:C.gray},chipTextOn:{color:C.blue},switchRow:{flexDirection:'row',alignItems:'center',padding:15,backgroundColor:C.pale,borderRadius:16,marginTop:14},switchTitle:{fontWeight:'900',color:C.navy},switchText:{color:C.gray,fontSize:12,lineHeight:17,marginTop:3,paddingRight:8},privacy:{flexDirection:'row',gap:9,padding:14,borderRadius:15,backgroundColor:C.pale,marginTop:14},privacyText:{flex:1,fontSize:12,color:C.gray,lineHeight:18},btn:{backgroundColor:C.blue,borderRadius:15,padding:16,alignItems:'center',marginTop:22},bt:{color:C.white,fontWeight:'900',fontSize:16},bottom:{fontSize:12,color:C.gray,textAlign:'center',marginTop:12}});