import React,{useCallback,useMemo,useState,useRef,useEffect}from'react';
import{SafeAreaView,ScrollView,View,Text,TextInput,Pressable,StyleSheet,Alert,KeyboardAvoidingView,Platform,Image,Keyboard}from'react-native';
import{useFocusEffect,useLocalSearchParams,router}from'expo-router';
import{Ionicons}from'@expo/vector-icons';
import{supabase}from'../lib/supabase';
import{useAuth}from'../lib/AuthContext';
import{C}from'../lib/theme';
import{threadComments}from'../lib/community';
import{chooseCommunityPhoto,uploadCommunityPhoto}from'../lib/communityPhoto';

export default function PostDetail(){
 const params=useLocalSearchParams<{id?:string|string[];commentId?:string}>();const id=Array.isArray(params.id)?params.id[0]:params.id;const{session}=useAuth();
 const[post,setPost]=useState<any>(null);const[comments,setComments]=useState<any[]>([]);const[body,setBody]=useState('');const[supported,setSupported]=useState(false);const[count,setCount]=useState(0);const[saved,setSaved]=useState(false);const[photoUrl,setPhotoUrl]=useState<string|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[commenting,setCommenting]=useState(false);const[replyTo,setReplyTo]=useState<any>(null);const[actionBusy,setActionBusy]=useState(false);const[editingComment,setEditingComment]=useState<any>(null);const[commentPhoto,setCommentPhoto]=useState<string|null>(null);const[commentUrls,setCommentUrls]=useState<Record<string,string>>({});const[commentSupport,setCommentSupport]=useState<any[]>([]);const[follow,setFollow]=useState<any>(null);const[followBusy,setFollowBusy]=useState(false);const scroll=useRef<ScrollView>(null);const composer=useRef<TextInput>(null);const positions=useRef<Record<string,number>>({});const[highlight,setHighlight]=useState<string|undefined>(params.commentId);useEffect(()=>{setHighlight(params.commentId);if(!params.commentId)return;const timer=setTimeout(()=>setHighlight(undefined),7000);return()=>clearTimeout(timer)},[params.commentId]);

 const load=useCallback(async(silent=false)=>{if(!id)return;if(!silent){setLoading(true);setError('');}
  const[p,c,r]=await Promise.all([
   supabase.from('posts').select('id,author_id,body,category,created_at,image_path,profiles!posts_author_id_fkey(display_name,city,region,avatar_url)').eq('id',id).single(),
   supabase.from('post_comments').select('id,post_id,author_id,parent_comment_id,body,image_path,edited_at,created_at,profiles!post_comments_author_id_fkey(display_name,avatar_url)').eq('post_id',id).order('created_at'),
   supabase.from('post_reactions').select('user_id').eq('post_id',id)
  ]);
  if(p.error){setError(p.error.code==='PGRST116'?'This post is no longer available.':p.error.message);setPost(null);if(!silent)setLoading(false);return}
  setPost(p.data);
  if(p.data?.image_path){const{data}=await supabase.storage.from('community-posts').createSignedUrl(p.data.image_path,3600);setPhotoUrl(data?.signedUrl||null)}else setPhotoUrl(null);
  if(!c.error){setComments(c.data||[]);const pairs=await Promise.all((c.data||[]).filter((x:any)=>x.image_path).map(async(x:any)=>{const {data}=await supabase.storage.from('community-posts').createSignedUrl(x.image_path,3600);return [x.id,data?.signedUrl]}));setCommentUrls(Object.fromEntries(pairs.filter(x=>x[1])));const ids=(c.data||[]).map((x:any)=>x.id);if(ids.length){const {data}=await supabase.from('comment_reactions').select('comment_id,user_id').in('comment_id',ids);setCommentSupport(data||[])}else setCommentSupport([]);}
  if(r.data){setCount(r.data.length);setSupported(r.data.some((x:any)=>x.user_id===session?.user.id))}
  if(session){const{data:f}=await supabase.from('post_follows').select('*').eq('user_id',session.user.id).eq('post_id',id).maybeSingle();setFollow(f);const{data:b}=await supabase.from('post_bookmarks').select('post_id').eq('user_id',session.user.id).eq('post_id',id).maybeSingle();setSaved(!!b)}
  if(!silent)setLoading(false);
 },[id,session?.user.id]);

 useFocusEffect(useCallback(()=>{load();if(!id)return;
  const commentsChannel=supabase.channel('post-comments-'+id).on('postgres_changes',{event:'*',schema:'public',table:'post_comments',filter:`post_id=eq.${id}`},()=>load(true)).subscribe();
  const reactionsChannel=supabase.channel('post-reactions-'+id).on('postgres_changes',{event:'*',schema:'public',table:'post_reactions',filter:`post_id=eq.${id}`},()=>load(true)).subscribe();
  const supportChannel=supabase.channel('comment-support-'+id).on('postgres_changes',{event:'*',schema:'public',table:'comment_reactions'},()=>load(true)).subscribe();return()=>{supabase.removeChannel(commentsChannel);supabase.removeChannel(reactionsChannel);supabase.removeChannel(supportChannel)}
 },[id,load]));

 async function toggle(){if(!session||!id||actionBusy)return;setActionBusy(true);const next=!supported;setSupported(next);setCount(v=>Math.max(0,v+(next?1:-1)));
  const q=next?await supabase.from('post_reactions').insert({post_id:id,user_id:session.user.id,reaction:'support'}):await supabase.from('post_reactions').delete().eq('post_id',id).eq('user_id',session.user.id);
  if(q.error){setSupported(!next);setCount(v=>Math.max(0,v+(next?-1:1)));Alert.alert('Could not update support',q.error.message)}setActionBusy(false);
 }
 async function bookmark(){if(!session||!id)return;const{error}=saved?await supabase.from('post_bookmarks').delete().eq('user_id',session.user.id).eq('post_id',id):await supabase.from('post_bookmarks').insert({user_id:session.user.id,post_id:id});if(error)return Alert.alert('Could not save post',error.message);setSaved(!saved)}
 async function followPost(mute=false){if(!session||!id||followBusy)return;setFollowBusy(true);const{error}=await supabase.from('post_follows').upsert({user_id:session.user.id,post_id:id,muted:mute});setFollowBusy(false);if(error)return Alert.alert('Could not update notifications',error.message);setFollow({muted:mute})}
 async function unfollow(){if(!session||followBusy)return;setFollowBusy(true);const{error}=await supabase.from('post_follows').delete().eq('user_id',session.user.id).eq('post_id',id);setFollowBusy(false);if(error)return Alert.alert('Could not unfollow',error.message);setFollow(null)}
 async function supportComment(x:any){if(!session||actionBusy)return;setActionBusy(true);const on=commentSupport.some(v=>v.comment_id===x.id&&v.user_id===session.user.id);const{error}=on?await supabase.from('comment_reactions').delete().eq('comment_id',x.id).eq('user_id',session.user.id):await supabase.from('comment_reactions').insert({comment_id:x.id,user_id:session.user.id});setActionBusy(false);if(error)return Alert.alert('Could not update support',error.message);await load(true)}
 async function chooseReplyPhoto(){try{const uri=await chooseCommunityPhoto();if(uri)setCommentPhoto(uri)}catch(e:any){Alert.alert('Could not add photo',e.message)}}
 function focusComposer(){setTimeout(()=>{scroll.current?.scrollToEnd({animated:true});composer.current?.focus()},100)}

 async function messageUser(userId:string){if(!session||userId===session.user.id)return;const{data,error}=await supabase.rpc('start_conversation',{other_user:userId});if(error)return Alert.alert('Could not start message',error.message);router.push({pathname:'/chat',params:{id:data}})}
 function openProfile(userId:string){if(!userId)return;router.push({pathname:'/member',params:{id:userId}})}
 async function remove(){Alert.alert('Delete post?','This will permanently remove the post and its comments.',[{text:'Cancel',style:'cancel'},{text:'Delete',style:'destructive',onPress:async()=>{const paths=[post.image_path,...comments.map(c=>c.image_path)].filter(Boolean);const{error}=await supabase.from('posts').delete().eq('id',id).eq('author_id',session?.user.id);if(error)return Alert.alert('Could not delete post',error.message);if(paths.length)await supabase.storage.from('community-posts').remove(paths);router.back()}}])}
 async function removeComment(commentId:string){if(!session)return;Alert.alert('Delete comment?','This comment and any replies to it will be permanently removed.',[{text:'Cancel',style:'cancel'},{text:'Delete',style:'destructive',onPress:async()=>{const removed=new Set([commentId]);let changed=true;while(changed){changed=false;for(const c of comments)if(removed.has(c.parent_comment_id)&&!removed.has(c.id)){removed.add(c.id);changed=true}}const paths=comments.filter(c=>removed.has(c.id)&&c.image_path&&c.author_id===session.user.id).map(c=>c.image_path);const{error}=await supabase.from('post_comments').delete().eq('id',commentId);if(error)return Alert.alert('Could not delete comment',error.message);if(paths.length)await supabase.storage.from('community-posts').remove(paths);load(true)}}])}
 async function comment(){const clean=body.trim();if(!clean||!session||!id||commenting)return;if(clean.length>1000)return Alert.alert('Comment too long','Keep comments under 1,000 characters.');setCommenting(true);let imagePath:string|null=null;
  try{if(commentPhoto)imagePath=await uploadCommunityPhoto(commentPhoto,session.user.id);
   const values:any={body:clean};if(imagePath)values.image_path=imagePath;
   const result=editingComment?await supabase.from('post_comments').update(values).eq('id',editingComment.id).eq('author_id',session.user.id):await supabase.from('post_comments').insert({...values,post_id:id,author_id:session.user.id,parent_comment_id:replyTo?.id||null});
   if(result.error)throw result.error;
   if(imagePath&&editingComment?.image_path)await supabase.storage.from('community-posts').remove([editingComment.image_path]);
   setBody('');setReplyTo(null);setEditingComment(null);setCommentPhoto(null);await load(true);
  }catch(e:any){if(imagePath)await supabase.storage.from('community-posts').remove([imagePath]);Alert.alert('Could not save comment',e.message)}finally{setCommenting(false)}
 }
 const ordered=useMemo(()=>threadComments(comments),[comments]);

 const renderComment=(x:any,isReply=false)=><View key={x.id} onLayout={e=>{positions.current[x.id]=e.nativeEvent.layout.y;if(highlight===x.id){scroll.current?.scrollTo({y:Math.max(0,e.nativeEvent.layout.y-30),animated:true});}}} style={[s.comment,isReply&&s.replyCard,highlight===x.id&&{borderWidth:2,borderColor:C.blue,backgroundColor:C.sky}]}>
  <View style={s.commentTop}>
   <Pressable onPress={()=>openProfile(x.author_id)} style={s.commentPerson}>
    {x.profiles?.avatar_url?<Image source={{uri:x.profiles.avatar_url}} style={s.commentAvatar}/>:<View style={s.commentFallback}><Text style={s.commentInitial}>{(x.profiles?.display_name||'M').charAt(0)}</Text></View>}
    <View style={{flex:1}}><Text style={s.commentName}>{x.profiles?.display_name||'Member'}</Text><Text style={s.commentTime}>{new Date(x.created_at).toLocaleString()}{x.edited_at?' · Edited':''}</Text></View>
   </Pressable>
   {x.author_id!==session?.user.id&&<Pressable hitSlop={8} onPress={()=>messageUser(x.author_id)} style={s.iconAction}><Ionicons name="chatbubble-outline" size={17} color={C.blue}/></Pressable>}
   {(x.author_id===session?.user.id||post.author_id===session?.user.id)&&<Pressable hitSlop={8} onPress={()=>removeComment(x.id)} style={s.iconAction}><Ionicons name="trash-outline" size={16} color={C.red}/></Pressable>}
  </View>
  {x.parent_comment_id&&<Text style={s.commentTime}>Replying to {comments.find(v=>v.id===x.parent_comment_id)?.profiles?.display_name||'a comment'}</Text>}
  <Text style={s.commentBody}>{x.body}</Text>{commentUrls[x.id]&&<Image source={{uri:commentUrls[x.id]}} style={s.postImage}/>}
  <View style={{flexDirection:'row',gap:16,flexWrap:'wrap'}}><Pressable onPress={()=>{setReplyTo(x);setEditingComment(null);setBody('');setCommentPhoto(null);focusComposer()}} style={s.replyBtn}><Ionicons name="return-down-forward-outline" size={15} color={C.blue}/><Text style={s.replyText}>Reply</Text></Pressable>
  <Pressable disabled={actionBusy} onPress={()=>supportComment(x)} style={s.replyBtn}><Ionicons name={commentSupport.some(v=>v.comment_id===x.id&&v.user_id===session?.user.id)?'heart':'heart-outline'} size={17} color={C.red}/><Text style={s.replyText}>{commentSupport.filter(v=>v.comment_id===x.id).length} Support</Text></Pressable>
  {x.author_id===session?.user.id&&<Pressable style={s.replyBtn} onPress={()=>{setEditingComment(x);setReplyTo(null);setCommentPhoto(null);setBody(x.body);focusComposer()}}><Text style={s.replyText}>Edit</Text></Pressable>}</View>
 </View>;

 if(loading)return <SafeAreaView style={s.safe}><Text style={s.loading}>Loading…</Text></SafeAreaView>;
 if(!post)return <SafeAreaView style={s.safe}><View style={s.page}><Pressable onPress={()=>router.back()}><Text style={s.back}>‹ Community</Text></Pressable><View style={s.comment}><Text style={s.commentName}>Post unavailable</Text><Text style={s.commentBody}>{error||'This post may have been deleted or is no longer visible.'}</Text><Pressable onPress={()=>load()} style={s.send}><Ionicons name="refresh" size={19} color={C.white}/></Pressable></View></View></SafeAreaView>;

 return <SafeAreaView style={s.safe}><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':'height'} keyboardVerticalOffset={Platform.OS==='ios'?8:0}><ScrollView ref={scroll} contentContainerStyle={s.page} keyboardShouldPersistTaps="handled" keyboardDismissMode={Platform.OS==='ios'?'interactive':'on-drag'} automaticallyAdjustKeyboardInsets={Platform.OS==='ios'}>
  <Pressable onPress={()=>router.back()}><Text style={s.back}>‹ Community</Text></Pressable>
  <View style={s.post}>
   <View style={s.postHeader}><Pressable onPress={()=>openProfile(post.author_id)} style={s.authorRow}>{post.profiles?.avatar_url?<Image source={{uri:post.profiles.avatar_url}} style={s.avatar}/>:<View style={s.avatarFallback}><Text style={s.initial}>{(post.profiles?.display_name||'M').charAt(0)}</Text></View>}<View><Text style={s.author}>{post.profiles?.display_name||'Member'}</Text><Text style={s.time}>{new Date(post.created_at).toLocaleString()}</Text></View></Pressable><Pressable onPress={()=>router.push({pathname:'/report',params:{type:'post',id:post.id}})}><Ionicons name="ellipsis-horizontal" size={22} color={C.gray}/></Pressable></View>
   <Text style={s.meta}>{post.category} · {[post.profiles?.city,post.profiles?.region].filter(Boolean).join(', ')||'T1Together'}</Text><Text style={s.body}>{post.body}</Text>{photoUrl&&<Image source={{uri:photoUrl}} style={s.postImage}/>}
   <View style={s.actions}><Pressable onPress={toggle} disabled={actionBusy} style={[s.support,supported&&s.supported]}><Ionicons name={supported?'heart':'heart-outline'} size={19} color={supported?C.red:C.blue}/><Text style={s.supportText}>{count} Support</Text></Pressable><Pressable onPress={bookmark} style={s.save}><Ionicons name={saved?'bookmark':'bookmark-outline'} size={19} color={C.blue}/><Text style={s.supportText}>{saved?'Saved':'Save'}</Text></Pressable>{post.author_id!==session?.user.id&&<Pressable onPress={()=>messageUser(post.author_id)} style={s.edit}><Ionicons name="chatbubble-outline" size={18} color={C.blue}/></Pressable>}{post.author_id===session?.user.id&&<><Pressable onPress={()=>router.push({pathname:'/create-post',params:{id:post.id}})} style={s.edit}><Ionicons name="create-outline" size={18} color={C.blue}/></Pressable><Pressable onPress={remove} style={s.delete}><Ionicons name="trash-outline" size={18} color={C.red}/></Pressable></>}</View>
  </View>
  <View style={{flexDirection:'row',gap:12,flexWrap:'wrap',marginTop:12}}><Pressable disabled={followBusy} style={s.replyBtn} onPress={()=>followPost(false)}><Text style={s.replyText}>{follow&&!follow.muted?'Following post':'Follow post'}</Text></Pressable><Pressable disabled={followBusy} style={s.replyBtn} onPress={()=>followPost(!follow?.muted)}><Text style={s.replyText}>{follow?.muted?'Unmute post':'Mute post'}</Text></Pressable>{follow&&<Pressable disabled={followBusy} style={s.replyBtn} onPress={unfollow}><Text style={s.replyText}>Unfollow / reset</Text></Pressable>}</View>
  <Text style={s.heading}>Comments</Text>
  {ordered.map(x=>renderComment(x,x.depth>0))}
  {comments.length===0&&<Text style={s.empty}>No comments yet. Be the first to join the conversation.</Text>}
  {editingComment&&<View style={s.replying}><Text style={s.replyingLabel}>Editing your comment</Text><Pressable onPress={()=>{setEditingComment(null);setBody('');setCommentPhoto(null)}}><Text style={s.replyText}>Cancel</Text></Pressable></View>}{replyTo&&<View style={s.replying}><View style={{flex:1}}><Text style={s.replyingLabel}>Replying to {replyTo.profiles?.display_name||'Member'}</Text><Text numberOfLines={1} style={s.replyingPreview}>{replyTo.body}</Text></View><Pressable onPress={()=>setReplyTo(null)}><Ionicons name="close-circle" size={22} color={C.gray}/></Pressable></View>}
  {commentPhoto&&<View><Image source={{uri:commentPhoto}} style={{height:150,borderRadius:12}}/><Pressable onPress={()=>setCommentPhoto(null)}><Text style={s.replyText}>Remove photo</Text></Pressable></View>}<Pressable style={s.replyBtn} onPress={chooseReplyPhoto}><Ionicons name="image-outline" size={20} color={C.blue}/><Text style={s.replyText}>{editingComment?.image_path?'Replace photo':'Add photo'}</Text></Pressable>
  <View style={s.compose}><TextInput ref={composer} maxLength={1000} style={s.input} value={body} onChangeText={setBody} placeholder={replyTo?'Write a reply…':'Add a supportive comment…'} multiline onFocus={()=>setTimeout(()=>Keyboard.scheduleLayoutAnimation?.({duration:250,easing:'keyboard'} as any),50)}/><Pressable style={[s.send,commenting&&{opacity:.5}]} onPress={comment} disabled={commenting||!body.trim()}><Ionicons name="send" size={19} color={C.white}/></Pressable></View>
 </ScrollView></KeyboardAvoidingView></SafeAreaView>
}

const s=StyleSheet.create({
 safe:{flex:1,backgroundColor:C.white},loading:{padding:30,color:C.gray},page:{padding:20,paddingBottom:50},back:{color:C.blue,fontWeight:'800',fontSize:16,marginTop:10,marginBottom:20},
 post:{padding:19,borderWidth:1,borderColor:C.line,borderRadius:20},authorRow:{flexDirection:'row',alignItems:'center',gap:9,flex:1},avatar:{width:40,height:40,borderRadius:20},avatarFallback:{width:40,height:40,borderRadius:20,backgroundColor:C.sky,alignItems:'center',justifyContent:'center'},initial:{fontWeight:'900',color:C.blue},time:{fontSize:10,color:C.gray,marginTop:2},postHeader:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},author:{fontWeight:'900',fontSize:17,color:C.navy},meta:{color:C.gray,fontSize:12,marginTop:3},body:{fontSize:17,lineHeight:25,color:C.navy,marginTop:17},postImage:{width:'100%',height:300,borderRadius:15,marginTop:15,resizeMode:'cover'},
 actions:{flexDirection:'row',flexWrap:'wrap',gap:5,marginTop:18},support:{flexDirection:'row',gap:7,alignItems:'center',paddingHorizontal:12,paddingVertical:8,borderRadius:18,backgroundColor:C.pale},supported:{backgroundColor:'#FFF1F1'},save:{flexDirection:'row',gap:6,alignItems:'center',paddingHorizontal:12,paddingVertical:8,borderRadius:18,backgroundColor:C.pale},edit:{marginLeft:'auto',padding:9},delete:{padding:9},supportText:{fontWeight:'800',color:C.navy},
 heading:{fontSize:20,fontWeight:'900',color:C.navy,marginTop:25,marginBottom:10},comment:{padding:14,borderRadius:15,backgroundColor:C.pale,marginBottom:9},replyCard:{marginLeft:34,backgroundColor:'#F7FAFD',borderLeftWidth:2,borderLeftColor:C.sky},commentTop:{flexDirection:'row',alignItems:'center',gap:7},commentPerson:{flex:1,flexDirection:'row',alignItems:'center',gap:9},commentAvatar:{width:32,height:32,borderRadius:16},commentFallback:{width:32,height:32,borderRadius:16,backgroundColor:C.sky,alignItems:'center',justifyContent:'center'},commentInitial:{fontSize:11,fontWeight:'900',color:C.blue},commentTime:{fontSize:9,color:C.gray,marginTop:2},iconAction:{width:34,height:34,alignItems:'center',justifyContent:'center'},commentName:{fontWeight:'900',color:C.navy,fontSize:13},commentBody:{color:C.navy,lineHeight:21,marginTop:5},replyBtn:{flexDirection:'row',alignItems:'center',gap:5,alignSelf:'flex-start',paddingVertical:7,paddingRight:12,marginTop:3},replyText:{fontSize:12,fontWeight:'800',color:C.blue},
 empty:{color:C.gray,paddingVertical:10},replying:{flexDirection:'row',alignItems:'center',gap:10,backgroundColor:C.pale,borderRadius:12,padding:10,marginTop:10},replyingLabel:{fontSize:12,fontWeight:'900',color:C.blue},replyingPreview:{fontSize:11,color:C.gray,marginTop:2},compose:{flexDirection:'row',gap:9,alignItems:'flex-end',marginTop:12},input:{flex:1,borderWidth:1,borderColor:C.line,borderRadius:16,padding:12,maxHeight:100,fontSize:15},send:{width:44,height:44,borderRadius:22,backgroundColor:C.blue,alignItems:'center',justifyContent:'center'}
});