import React,{useCallback,useState}from'react';
import{SafeAreaView,ScrollView,View,Text,Pressable,StyleSheet,Image,Alert,ActivityIndicator}from'react-native';
import{useFocusEffect,useLocalSearchParams,router}from'expo-router';
import{Ionicons}from'@expo/vector-icons';
import{supabase}from'../lib/supabase';
import{useAuth}from'../lib/AuthContext';
import{C}from'../lib/theme';

export default function SupplyDetail(){
 const params=useLocalSearchParams<{id?:string|string[]}>();const id=Array.isArray(params.id)?params.id[0]:params.id;const{session}=useAuth();const[item,setItem]=useState<any>(null);const[loading,setLoading]=useState(true);
 const load=useCallback(async()=>{if(!id||!session)return;setLoading(true);const{data,error}=await supabase.from('supply_posts').select('id,owner_id,post_type,category,item_name,device_family,quantity,details,radius_miles,status,created_at,expires_at,profiles!supply_posts_owner_id_fkey(display_name,city,region,avatar_url)').eq('id',id).maybeSingle();if(error)Alert.alert('Could not open request',error.message);setItem(data);setLoading(false)},[id,session?.user?.id]);useFocusEffect(useCallback(()=>{load()},[load]));
 async function message(){if(!item)return;const{data,error}=await supabase.rpc('start_conversation',{other_user:item.owner_id});if(error)return Alert.alert('Could not start message',error.message);if(data)router.push({pathname:'/chat',params:{id:data}})}
 async function renew(){const{error}=await supabase.rpc('renew_supply_post',{post_id:id});if(error)return Alert.alert('Could not renew post',error.message);load()}
 async function close(){const{error}=await supabase.from('supply_posts').update({status:'closed'}).eq('id',id).eq('owner_id',session?.user.id);if(error)return Alert.alert('Could not close post',error.message);router.back()}
 if(loading)return <SafeAreaView style={s.safe}><ActivityIndicator style={{marginTop:50}} color={C.blue}/></SafeAreaView>;
 if(!item)return <SafeAreaView style={s.safe}><View style={s.page}><Pressable onPress={()=>router.back()}><Text style={s.back}>‹ Supply Locker</Text></Pressable><View style={s.empty}><Text style={s.emptyTitle}>Request unavailable</Text><Text style={s.muted}>This Supply Locker post may have been closed, expired, or is no longer visible.</Text></View></View></SafeAreaView>;
 const own=item.owner_id===session?.user.id;
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}><Pressable onPress={()=>router.back()}><Text style={s.back}>‹ Supply Locker</Text></Pressable><View style={s.owner}><View style={s.avatar}>{item.profiles?.avatar_url?<Image source={{uri:item.profiles.avatar_url}} style={s.photo}/>:<Text style={s.initial}>{(item.profiles?.display_name||'M').charAt(0).toUpperCase()}</Text>}</View><View style={{flex:1}}><Text style={s.person}>{item.profiles?.display_name||'T1Together Member'}</Text><Text style={s.location}>{[item.profiles?.city,item.profiles?.region].filter(Boolean).join(', ')||'T1Together community'}</Text></View></View><View style={s.card}><View style={s.row}><View style={[s.tag,item.post_type==='offer'&&s.offerTag]}><Text style={[s.tagText,item.post_type==='offer'&&s.offerTagText]}>{item.post_type==='need'?'NEEDED':'OFFERED'}</Text></View><Text style={s.category}>{item.category}</Text></View><Text style={s.h}>{item.item_name}</Text>{item.quantity?<Text style={s.line}>Quantity: {item.quantity}</Text>:null}{item.device_family?<Text style={s.line}>Device: {item.device_family}</Text>:null}{item.details?<><Text style={s.label}>Details</Text><Text style={s.details}>{item.details}</Text></>:null}<Text style={s.meta}>Nearby radius: {item.radius_miles} miles</Text>{item.expires_at?<Text style={s.meta}>Expires {new Date(item.expires_at).toLocaleString()}</Text>:null}</View><View style={s.notice}><Ionicons name="shield-checkmark-outline" size={20} color={C.blue}/><Text style={s.noticeText}>Supply Locker helps members connect. No buying or selling. Coordinate any handoff privately after connecting.</Text></View>{own?<View style={s.actions}><Pressable style={s.primary} onPress={renew}><Text style={s.primaryText}>Renew 14 Days</Text></Pressable><Pressable style={s.secondary} onPress={close}><Text style={s.closeText}>Mark Closed</Text></Pressable></View>:<Pressable style={s.primary} onPress={message}><Ionicons name="chatbubble-outline" size={18} color={C.white}/><Text style={s.primaryText}>Message {item.profiles?.display_name||'Member'}</Text></Pressable>}</ScrollView></SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:C.white},page:{padding:20,paddingBottom:45},back:{color:C.blue,fontWeight:'800',fontSize:16,marginTop:10,marginBottom:20},owner:{flexDirection:'row',alignItems:'center',marginBottom:15},avatar:{width:48,height:48,borderRadius:24,backgroundColor:C.sky,alignItems:'center',justifyContent:'center',overflow:'hidden',marginRight:11},photo:{width:48,height:48},initial:{fontWeight:'900',color:C.blue},person:{fontSize:16,fontWeight:'900',color:C.navy},location:{fontSize:12,color:C.gray,marginTop:3},card:{borderWidth:1,borderColor:C.line,borderRadius:20,padding:19},row:{flexDirection:'row',alignItems:'center',gap:8},tag:{backgroundColor:C.sky,paddingHorizontal:8,paddingVertical:4,borderRadius:9},tagText:{fontSize:10,fontWeight:'900',color:C.blue},offerTag:{backgroundColor:'#EAF9F2'},offerTagText:{color:C.green},category:{fontSize:11,color:C.gray,fontWeight:'800'},h:{fontSize:25,fontWeight:'900',color:C.navy,marginTop:14},line:{fontSize:14,color:C.navy,marginTop:10},label:{fontSize:13,fontWeight:'900',color:C.navy,marginTop:18},details:{fontSize:15,lineHeight:22,color:C.gray,marginTop:5},meta:{fontSize:11,color:C.gray,marginTop:13},notice:{flexDirection:'row',gap:9,backgroundColor:C.pale,padding:14,borderRadius:15,marginTop:14},noticeText:{flex:1,color:C.gray,fontSize:12,lineHeight:18},primary:{flexDirection:'row',gap:7,alignItems:'center',justifyContent:'center',backgroundColor:C.blue,padding:14,borderRadius:14,marginTop:16},primaryText:{color:C.white,fontWeight:'900'},secondary:{backgroundColor:C.pale,padding:14,borderRadius:14,alignItems:'center',marginTop:9},closeText:{color:C.green,fontWeight:'900'},actions:{marginTop:0},empty:{padding:22,backgroundColor:C.pale,borderRadius:18},emptyTitle:{fontSize:18,fontWeight:'900',color:C.navy},muted:{color:C.gray,lineHeight:20,marginTop:6}});
