import React,{useCallback,useState} from 'react';
import {View,Text,Alert,Linking,Platform,Share} from 'react-native';
import {useFocusEffect,router} from 'expo-router';
import Constants from 'expo-constants';
import * as Notifications from 'expo-notifications';
import * as Location from 'expo-location';
import {Screen,Action,ui} from '../components/Screen';
import {supabase} from '../lib/supabase';
import {useAuth} from '../lib/AuthContext';
import {registerPush} from '../lib/notifications';
import {permissionDescription,diagnosticSummary} from '../lib/troubleshooting';
export default function Troubleshooting(){
 const{session}=useAuth();const[permission,setPermission]=useState<any>(null);const[location,setLocation]=useState('Checking…');const[connection,setConnection]=useState('Not checked');const[checkedAt,setCheckedAt]=useState<string|null>(null);const[busy,setBusy]=useState<string|null>(null);const[registration,setRegistration]=useState('');
 const version=Constants.expoConfig?.version||'Unknown';const build=Platform.OS==='ios'?Constants.platform?.ios?.buildNumber||'Unknown':String(Constants.platform?.android?.versionCode||Constants.expoConfig?.android?.versionCode||'Unknown');const timezone=Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC';
 const refresh=useCallback(async()=>{try{const[p,l]=await Promise.all([Notifications.getPermissionsAsync(),Location.getForegroundPermissionsAsync()]);setPermission(p);setLocation(l.granted?'Allowed':'Not enabled')}catch{setLocation('Could not check permissions')}},[]);
 useFocusEffect(useCallback(()=>{refresh()},[refresh]));
 async function checkConnection(){if(busy)return;if(!session){setConnection('Not signed in');return}setBusy('connection');const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),10000);try{const{data,error}=await supabase.from('profiles').select('id').eq('id',session.user.id).abortSignal(controller.signal).maybeSingle();setConnection(!error&&data?'Connected':'Could not connect. Check internet and try again.');setCheckedAt(new Date().toLocaleString())}catch{setConnection('Could not connect. Check internet and try again.')}finally{clearTimeout(timer);setBusy(null)}}
 async function enablePush(){if(!session||busy)return;setBusy('push');try{const result=await registerPush(session.user.id);setRegistration(result.ok?'This device is registered for push alerts.':result.reason==='permission'?'Enable notifications in your phone settings, then retry.':result.reason==='project'?'This build needs its notification configuration checked.':'Could not register this device. Check your connection, then retry.');await refresh()}catch{setRegistration('Could not register notifications. Try again.')}finally{setBusy(null)}}
 async function testNotification(){if(busy)return;setBusy('test');try{const p=await Notifications.getPermissionsAsync();setPermission(p);if(!p.granted&&p.ios?.status!==Notifications.IosAuthorizationStatus.PROVISIONAL){Alert.alert('Enable notifications first','Use Enable Notifications or open your phone settings.');return}await Notifications.scheduleNotificationAsync({content:{title:'T1DReach notification test',body:'Your phone can display T1DReach alerts.',sound:'default',data:{route:'/troubleshooting'}},trigger:{type:Notifications.SchedulableTriggerInputTypes.TIME_INTERVAL,seconds:5,...(Platform.OS==='android'?{channelId:'default'}:{})}});Alert.alert('Test scheduled','A local test alert should appear in about five seconds.')}catch{Alert.alert('Could not schedule test','Check notification permissions and try again.')}finally{setBusy(null)}}
 async function openPhoneSettings(){try{await Linking.openSettings()}catch{Alert.alert('Open phone settings','Find T1DReach in your phone’s Settings app.')}}
 async function share(){try{await Share.share({message:diagnosticSummary({version,build,platform:`${Platform.OS} ${Platform.Version}`,permission:permissionDescription(permission),connection,timezone})})}catch{Alert.alert('Could not share','Please try again.')}}
 return <Screen title="App & Notification Help"><Text style={ui.text}>Check common account, connection and notification issues here.</Text><View style={ui.card}><Text accessibilityRole="header" style={ui.heading}>This app</Text><Text selectable style={ui.text}>Version: {version}{'\n'}Build: {build}{'\n'}Device: {Platform.OS} {Platform.Version}{'\n'}Account: {session?'Signed in':'Not signed in'}</Text><Text style={[ui.text,{marginTop:8}]}>Install the latest available build from TestFlight on iPhone, or your Android testing link.</Text></View>
 <View style={ui.card}><Text accessibilityRole="header" style={ui.heading}>Connection</Text><Text accessibilityLiveRegion="polite" style={ui.text}>{connection}</Text>{checkedAt&&<Text style={ui.text}>Last checked: {checkedAt}</Text>}<Action label="Check connection" busy={busy==='connection'} disabled={!!busy} onPress={checkConnection}/></View>
 <View style={ui.card}><Text accessibilityRole="header" style={ui.heading}>Notifications</Text><Text style={ui.text}>{permission?permissionDescription(permission):'Checking permission…'}</Text><Text style={[ui.text,{marginTop:8}]}>Check both your phone’s permission and the app’s alert preferences. Quiet hours silence push alerts, including T1 Beacon.</Text><Action label="Enable / Re-register Notifications" busy={busy==='push'} disabled={!!busy} onPress={enablePush}/>{!!registration&&<Text accessibilityLiveRegion="polite" style={[ui.text,{marginTop:10}]}>{registration}</Text>}<Action secondary label="Send local test alert" busy={busy==='test'} disabled={!!busy} onPress={testNotification}/><Text style={[ui.text,{marginTop:10}]}>The local test checks phone alerts. It does not test server delivery or quiet hours. To test a real push, have another member reply to your comment while the app is in the background.</Text><Action secondary label="Open phone settings" onPress={openPhoneSettings}/><Action secondary label="Open alert preferences" onPress={()=>router.push({pathname:'/settings',params:{section:'notifications'}})}/></View>
 <View style={ui.card}><Text accessibilityRole="header" style={ui.heading}>Nearby & Location</Text><Text style={ui.text}>Location permission: {location}. Nearby matching also needs an updated approximate location and your privacy preferences.</Text><Action secondary label="Open location & privacy settings" onPress={()=>router.push({pathname:'/settings',params:{section:'privacy'}})}/></View>
 <View style={ui.card}><Text accessibilityRole="header" style={ui.heading}>Trouble signing in?</Text><Text style={ui.text}>Confirm your email address, check your spam folder, and use Forgot Password on the sign-in screen if needed. If an email request hits a limit, wait before requesting it again.</Text></View><Action secondary label="Share troubleshooting info" onPress={share}/><Text style={[ui.text,{marginTop:10}]}>The shared summary includes the app version, build, device platform, notification permission, connection status and time zone.</Text></Screen>;
}
