import React,{useCallback,useState}from'react';
import{SafeAreaView,ScrollView,View,Text,Pressable,StyleSheet,RefreshControl ,Image}from'react-native';
import{useFocusEffect,router}from'expo-router';
import{Ionicons}from'@expo/vector-icons';
import{supabase}from'../../lib/supabase';
import{useAuth}from'../../lib/AuthContext';
import{C}from'../../lib/theme';

type Profile={display_name:string;city:string|null;region:string|null;helper_enabled:boolean;role:string;avatar_url:string|null};
type Post={id:string;body:string;category:string;created_at:string;profiles:any};

export default function Home(){
 const{session}=useAuth();const[profile,setProfile]=useState<Profile|null>(null);const[posts,setPosts]=useState<Post[]>([]);const[refreshing,setRefreshing]=useState(false);const[unread,setUnread]=useState(0);
 const load=useCallback(async()=>{if(!session)return;const[p,feed,n]=await Promise.all([
  supabase.from('profiles').select('display_name,city,region,helper_enabled,avatar_url,role,avatar_url').eq('id',session.user.id).single(),
  supabase.from('posts').select('id,body,category,created_at,profiles!posts_author_id_fkey(display_name,city,region,avatar_url)').order('created_at',{ascending:false}).limit(3)
 ,supabase.rpc('my_unread_notification_count')]);if(p.data)setProfile(p.data);if(feed.data)setPosts(feed.data as Post[]);setUnread(Number(n.data||0));},[session]);
 useFocusEffect(useCallback(()=>{load()},[load]));
 async function refresh(){setRefreshing(true);await load();setRefreshing(false)}
 const first=profile?.display_name?.split(' ')[0]||'there';
 return <SafeAreaView style={s.safe}><ScrollView style={s.scroll} contentContainerStyle={s.page} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={refresh}/>}>
  <View style={s.top}><View style={{flex:1}}><Text style={s.h}>Hi, {first} 💙</Text><Text style={s.location}>{profile?.city?[profile.city,profile.region].filter(Boolean).join(', '):'Your T1D community'}</Text></View><Pressable style={s.iconBtn} onPress={()=>router.push('/notifications')}><Ionicons name="notifications-outline" size={22} color={C.navy}/>{unread>0&&<View style={s.badge}><Text style={s.badgeText}>{unread>9?'9+':unread}</Text></View>}</Pressable><Pressable style={s.avatar} onPress={()=>router.push('/settings')}>{profile?.avatar_url?<Image source={{uri:profile.avatar_url}} style={s.avatarPhoto}/>:<Text style={s.avatarText}>{(profile?.display_name||'M').charAt(0).toUpperCase()}</Text>}</Pressable></View>
  <View style={s.welcomeCard}><View style={{flex:1}}><Text style={s.welcomeTitle}>{profile?.helper_enabled?'Helper Mode is on':'You’re part of T1Together'}</Text><Text style={s.welcomeText}>{profile?.helper_enabled?'You can receive nearby requests when someone needs community help.':'Connect with nearby members, share experiences and ask for help when you need it.'}</Text></View><Ionicons name={profile?.helper_enabled?'heart':'people-outline'} size={25} color={profile?.helper_enabled?C.green:C.blue}/></View><Pressable style={s.composer} onPress={()=>router.push('/create-post')}><View style={s.composerIcon}><Ionicons name="create-outline" size={21} color={C.blue}/></View><Text style={s.composerText}>Share something with the community</Text><Ionicons name="chevron-forward" size={20} color={C.gray}/></Pressable>
  <View style={s.resourceRow}><Pressable style={s.resource} onPress={()=>router.push('/resources')}><Ionicons name="book-outline" size={21} color={C.blue}/><View style={{flex:1}}><Text style={s.resourceTitle}>T1D Guide</Text><Text style={s.resourceText}>Newly diagnosed, devices, lows, school, travel & more</Text></View><Ionicons name="chevron-forward" size={19} color={C.gray}/></Pressable></View><Text style={s.section}>Quick Help</Text><View style={s.actions}>
   <Pressable style={[s.action,s.beacon]} onPress={()=>router.push({pathname:'/create-help',params:{mode:'beacon'}})}><Ionicons name="radio" size={25} color={C.red}/><Text style={s.actionTitle}>T1 Beacon</Text><Text style={s.actionText}>Ask nearby helpers</Text></Pressable>
   <Pressable style={s.action} onPress={()=>router.push('/supply-locker')}><Ionicons name="cube-outline" size={25} color={C.blue}/><Text style={s.actionTitle}>Supply Locker</Text><Text style={s.actionText}>Request or offer supplies</Text></Pressable>
  </View>
  <View style={s.sectionRow}><Text style={s.section}>Community</Text><Pressable onPress={()=>router.push('/(tabs)/community')}><Text style={s.see}>See all</Text></Pressable></View>
  {posts.length===0?<View style={s.empty}><Text style={s.emptyTitle}>Start the conversation</Text><Text style={s.emptyText}>Your community feed is ready. Share the first post.</Text></View>:posts.map(p=><Pressable key={p.id} style={s.post} onPress={()=>router.push({pathname:'/post-detail',params:{id:p.id}})}><View style={s.postTop}><View style={s.smallAvatar}>{p.profiles?.avatar_url?<Image source={{uri:p.profiles.avatar_url}} style={s.smallPhoto}/>:<Text style={s.smallInitial}>{(p.profiles?.display_name||'M').charAt(0).toUpperCase()}</Text>}</View><View style={{flex:1}}><Text style={s.author}>{p.profiles?.display_name||'T1Together Member'}</Text><Text style={s.meta}>{p.category} · {new Date(p.created_at).toLocaleDateString()}</Text></View></View><Text style={s.body}>{p.body}</Text></Pressable>)}
  <Text style={s.note}>T1Together is peer support, not medical advice. For emergencies, contact emergency services.</Text>
 </ScrollView></SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:C.white},scroll:{flex:1},page:{padding:20,paddingBottom:38},top:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:12},h:{fontSize:32,fontWeight:'900',color:C.navy,marginTop:3},location:{color:C.gray,fontSize:14,marginTop:3},avatar:{width:46,height:46,borderRadius:23,backgroundColor:C.sky,alignItems:'center',justifyContent:'center',marginLeft:8},avatarPhoto:{width:46,height:46},smallPhoto:{width:34,height:34},smallInitial:{fontSize:13,fontWeight:'900',color:C.blue},avatarText:{fontSize:18,fontWeight:'900',color:C.blue},iconBtn:{width:44,height:44,borderRadius:22,backgroundColor:C.pale,alignItems:'center',justifyContent:'center',position:'relative'},badge:{position:'absolute',right:-2,top:-3,minWidth:18,height:18,borderRadius:9,backgroundColor:C.red,alignItems:'center',justifyContent:'center',paddingHorizontal:4},badgeText:{fontSize:9,fontWeight:'900',color:C.white},welcomeCard:{flexDirection:'row',alignItems:'center',gap:12,backgroundColor:C.pale,padding:16,borderRadius:18,marginTop:20},welcomeTitle:{fontWeight:'900',color:C.navy,fontSize:15},welcomeText:{color:C.gray,fontSize:12,lineHeight:18,marginTop:4},composer:{marginTop:12,borderWidth:1,borderColor:C.line,borderRadius:18,padding:14,flexDirection:'row',alignItems:'center',backgroundColor:C.white},composerIcon:{width:36,height:36,borderRadius:18,backgroundColor:C.sky,alignItems:'center',justifyContent:'center'},composerText:{flex:1,color:C.gray,fontSize:16,marginLeft:12},section:{fontSize:20,fontWeight:'900',color:C.navy,marginTop:25,marginBottom:12},actions:{flexDirection:'row',gap:12},action:{flex:1,padding:16,borderRadius:18,backgroundColor:C.pale,minHeight:124},beacon:{backgroundColor:'#FFF4F3'},actionTitle:{fontSize:16,fontWeight:'900',color:C.navy,marginTop:10},actionText:{fontSize:13,color:C.gray,marginTop:3},sectionRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},see:{color:C.blue,fontWeight:'800',marginTop:15},empty:{padding:20,borderRadius:18,backgroundColor:C.pale},emptyTitle:{fontWeight:'900',fontSize:17,color:C.navy},emptyText:{color:C.gray,marginTop:5,lineHeight:20},post:{padding:17,borderRadius:18,borderWidth:1,borderColor:C.line,marginBottom:12},postTop:{flexDirection:'row',alignItems:'center'},smallAvatar:{width:34,height:34,borderRadius:17,backgroundColor:C.sky,alignItems:'center',justifyContent:'center',marginRight:10},author:{fontWeight:'900',color:C.navy},meta:{fontSize:12,color:C.gray,marginTop:2},body:{fontSize:16,lineHeight:23,color:C.navy,marginTop:12},resourceRow:{marginTop:18},resource:{flexDirection:'row',alignItems:'center',gap:11,padding:15,borderRadius:17,backgroundColor:C.pale},resourceTitle:{fontWeight:'900',color:C.navy},resourceText:{fontSize:12,color:C.gray,marginTop:2},note:{fontSize:12,lineHeight:17,color:C.gray,textAlign:'center',marginTop:25,paddingHorizontal:12}});